# conda env create --file environment.yml
# mamba env create --file environment.yml
name: neuronal_networks_examples
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - matplotlib
  - pip
  - scikit-learn
  - seaborn
  - keras
  - notebook
  - tensorflow
  